#Update all the sections by editing the data.yml file inside _data folder.

# Site Settings
title: Cody White's Resume
url: 'https://codyrwhite.github.io'
baseurl: '/online-cv' #change it according to your repository name
description: A little bit about me and what I have done. 
favicon: 'https://avatars3.githubusercontent.com/u/56890437?s=96&v=4'
fluid_icon: 'https://avatars3.githubusercontent.com/u/56890437?s=96&v=4'
# Style will be applied only after restarting the build or serve. Just choose one of the options.
theme_skin: ceramic # blue turquoise green berry orange ceramic
chrome_mobile_color: #use hex colors (ex:#1976d2) or leave empty if you don't want a color for chrome mobile searchbar

## Thumbnail Information
google_meta: true
twitter_meta: true
facebook_meta: true
thumbnail_image: 'https://avatars3.githubusercontent.com/u/56890437?s=96&v=4'
twitter_card: Summary
twitter_id: '@CodyWhite_'
og_type: Blog

# Tracker
analytics: UA-12472657-5
site_verification: 'E35k6R0VeQ_Tz4WIdIA0B8JUbFqouNeUrRfiqktZmfg'



# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Build settings
compress-site: yes

encoding: "utf-8"

compress_html: # - http://jch.penibelst.de/
  clippings: all
  comments: #["<!-- ", " -->"]
  endings: all
  ignore:
    envs: development
  blanklines: true
  profile: true
  startings: [html, head, body]

# Development Settings
port: 4000
host: 0.0.0.0
safe: false
